language: go
sudo: false

go:
  - 1.5.3
  - 1.6
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install: go get -t ./...

script:
  - go test -v ./...
  - if [ "$TRAVIS_GO_VERSION" = "1.6" ]; then go test -race -v ./...; fi
  - go vet ./...
  - diff <(gofmt -d .) <(echo -n "")
  - if [ "$TRAVIS_GO_VERSION" = "1.6" ]; then $HOME/gopath/bin/goveralls -service=travis-ci || true; fi
