language: go

go:
  - 1.5.3
  - 1.6
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install: go get -t ./...

script:
  - go test -v ./...
  - go vet ./...
  - diff <(gofmt -d .) <(echo -n "")
  - if [ "$(go version | awk '{print $3}')" = "go1.6" ]; then $HOME/gopath/bin/goveralls -service=travis-ci || true; fi
