language: go
sudo: false

env:
  global:
    - APP_NAME=yandex-weather-cli

matrix:
  fast_finish: true
  include:
    - go: 1.15.x
    - go: 1.x
      env: IS_LATEST_GO=true
    - go: master
  allow_failures:
    - go: master

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/kisielk/errcheck

install: go get -t ./...

script:
  - go test -race -v ./...
  - go vet ./...
  - errcheck ./...
  - diff <(gofmt -d .) <(echo -n "")
  - if [[ "$IS_LATEST_GO" == "true" ]] && [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      go test -covermode=count -coverprofile=profile.cov ./... && goveralls -coverprofile=profile.cov -service=travis-ci || true;
    fi

before_deploy:
  - curl -SL https://raw.githubusercontent.com/msoap/etc/master/golang-cross-build/golang-cross-build.sh > $GOPATH/bin/golang-cross-build.sh
  - chmod 700 $GOPATH/bin/golang-cross-build.sh
  - gem install --no-ri --no-rdoc fpm
  - golang-cross-build.sh $APP_NAME
  - ls -l *.zip *.tar.gz *.deb

deploy:
  provider: releases
  api_key:
    secure: blcSNUN/RbiY7thbkyvwjL9QpNUgkkulxWG0TilnuVUZ22qAkaTcOS4A1AVrJZJkMzXce9QRHiSTEAJZOxlDQXyip8wKZETLXxNQl0i3R4CYVN7p8DapOD/AEY8YXfpwLEFWF/fWZEDv3SzeVjp8kvpan+mH3AsUwMVIFyOpZUDdYV1Uhu57T7QBS5FHnQgDqpcHHgV6f3fii6ZNfhew46ix5+7xqTyaN8Bgn72Yu+OKemi9GxxrokUVrH1GliOYX9UEyBmiMIEHFaFQeOTQYQg4/BvC5l8F7JLrAu/vZJvqM333SJhwn/zkPsxn68h2gY2Hu24oK8jmakwJ25lo+pp4mu/2nqCaTUwH9lV4UlXLdhlqf00nCQhdUG9vvU0wB62BtCpOjd3ZdSxZVkh9eZtOt/1hAGRPsDAi45RgEaeNpOfGkoGkr3PPDTWpBM6Un5DiGX1fFWMgK1XfjZpjo+a6xgyCTVK/nd/ZtfPJhx2VuVB4Crnv34luLtZMYIdMZbx0ErPKMrzMEQS8tjPLCoSaGNy+NbrQLNT7p1Ypd355AuB3iqKQMiIVLMvfxiiJOuxDHj0wTrOwdgL6d7Wd5rvMiS3y8aSm95lnC/JeyTfHNxUS30IMZtMxm2/wnsRaJFA/1MELYybkkcztOyCXL/E138kOiXDqQW7T/qXw4OI=
  file_glob: "true"
  file:
    - "*.zip"
    - "*.tar.gz"
    - "*.deb"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: $IS_LATEST_GO = true
    repo: msoap/$APP_NAME
