name: yandex-weather-cli
version: '1.10'
summary: Yandex weather cli
description: Command line interface for Yandex weather service
grade: stable
confinement: strict

parts:
  yandex-weather-cli:
    source: .
    plugin: go
    go-importpath: github.com/msoap/yandex-weather-cli
    after: [go]
  go:
    source-tag: go1.10

apps:
  yandex-weather-cli:
    command: yandex-weather-cli
    plugs: [network]
