name: yandex-weather-cli
version: 1.14
summary: Yandex weather cli
description: Command line interface for Yandex weather service
grade: stable
confinement: strict
base: core18
parts:
  yandex-weather-cli:
    plugin: go
    go-importpath: github.com/msoap/yandex-weather-cli
    source: .
    source-type: git

apps:
  yandex-weather-cli:
    command: bin/yandex-weather-cli
    plugs: [network]
